electricalConsumptionPower <- read.table("ExData_Plotting1/household_power_consumption.txt",sep=";", header = TRUE)
electricalConsumptionPower$DateTime <- paste(as.character(electricalConsumptionPower$Date), " ", as.character(electricalConsumptionPower$Time))
electricalConsumptionPower$Date <-as.Date(electricalConsumptionPower$Date,"%d/%m/%Y")
electricalConsumptionPower$DateTime <- strptime(electricalConsumptionPower$DateTime,"%d/%m/%Y %H:%M:%S")
electricalConsumptionPowerSubset <-electricalConsumptionPower[(electricalConsumptionPower$Date>="2007-02-01"& electricalConsumptionPower$Date<="2007-02-02"), ]
electricalConsumptionPowerSubset$Global_active_power <-as.character(electricalConsumptionPowerSubset$Global_active_power)
electricalConsumptionPowerSubset$Global_active_power <-as.numeric(electricalConsumptionPowerSubset$Global_active_power)
electricalConsumptionPowerSubset$Sub_metering_1 <- as.character(electricalConsumptionPowerSubset$Sub_metering_1)
electricalConsumptionPowerSubset$Sub_metering_1 <- as.numeric(electricalConsumptionPowerSubset$Sub_metering_1)
electricalConsumptionPowerSubset$Sub_metering_2 <- as.character(electricalConsumptionPowerSubset$Sub_metering_2)
electricalConsumptionPowerSubset$Sub_metering_2 <- as.numeric(electricalConsumptionPowerSubset$Sub_metering_2)
electricalConsumptionPowerSubset$Sub_metering_3 <- as.character(electricalConsumptionPowerSubset$Sub_metering_3)
electricalConsumptionPowerSubset$Sub_metering_3 <- as.numeric(electricalConsumptionPowerSubset$Sub_metering_3)
png("plot3.png",width=480,height=480)
plot(electricalConsumptionPowerSubset$DateTime,electricalConsumptionPowerSubset$Sub_metering_1,type="l", ylab="Energy sub metering", xlab="")
lines(electricalConsumptionPowerSubset$DateTime,electricalConsumptionPowerSubset$Sub_metering_2, col="red")
lines(electricalConsumptionPowerSubset$DateTime,electricalConsumptionPowerSubset$Sub_metering_3, col="blue")
legend("topright",legend=c("Sub metering 1","Sub metering 2","Sub metering 3"), col=c("black","red","blue"), lty=1)
dev.off()